version: "3.1"

services:
  omada-controller:
    container_name: omada-controller
    hostname: omada-controller
    #image: auster/omada-controller:5.15
    #image: auster/omada-controller:5.14
    image: ghcr.io/danieldaf/omada-controller:5.14
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs

volumes:
  omada-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./omada-data
  omada-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./omada-logs

networks:
  default:
    name: "auster_network"
    driver: bridge
