-- TIPO_OPERACION:
-- VOUCHER_TYPE: BY_TIME, UNKNOWN
-- VOUCHER_CURRENCY: USD, ARS

CREATE TABLE AUDITORIA (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    TIPO_OPERACION VARCHAR(6) NOT NULL,
    USERNAME VARCHAR(64) DEFAULT NULL,

    CLIENT_DEVICE_MAC VARCHAR(20) DEFAULT NULL,
    CLIENT_DEVICE_IP VARCHAR(20) DEFAULT NULL,

    VOUCHER_NAME VARCHAR(32) DEFAULT NULL,
    VOUCHER_TYPE VARCHAR(32) DEFAULT NULL,
    VOUCHER_CURRENCY VARCHAR(6) DEFAULT NULL,
    VOUCHER_PRICE DECIMAL(9,3) DEFAULT NULL,

    RESULT VARCHAR(128) NOT NULL,

    PRIMARY KEY(ID)
);

